name: Build Nintendo DS Google Balls

on:
  push:
    branches: [ nds ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    defaults:
      run:
        working-directory: ./nds

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup devkitPro environment
      run: |
        echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
        echo "DEVKITARM=/opt/devkitpro/devkitARM" >> $GITHUB_ENV
        echo "PATH=/opt/devkitpro/devkitARM/bin:/opt/devkitpro/tools/bin:$PATH" >> $GITHUB_ENV
        
    - name: Verify devkitPro installation
      run: |
        echo "DEVKITPRO: $DEVKITPRO"
        echo "DEVKITARM: $DEVKITARM"
        ls -la /opt/devkitpro/
        ls -la /opt/devkitpro/devkitARM/bin/
        arm-none-eabi-gcc --version
        
    - name: Create source directory
      run: |
        mkdir -p source
        cp main.cpp source/main.cpp
        
    - name: Build Nintendo DS ROM
      run: |
        make clean
        make -j$(nproc)
        
    - name: Upload NDS ROM artifact
      uses: actions/upload-artifact@v4
      with:
        name: google-balls-nds-rom
        path: ./nds/google-balls-nds.nds
        
    - name: Upload debug info
      uses: actions/upload-artifact@v4
      with:
        name: debug-files
        path: |
          ./nds/google-balls-nds.elf
          build/